import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, ArrowRight, ExternalLink, X, Map, BookOpen, Mail, CheckCircle2 } from 'lucide-react'
import './style.css'
import { stops, type Stop } from './portfolioData'

function Character({moving}:{moving:boolean}){return <div className={`character ${moving?'walking':''}`} aria-label="걷는 캐릭터"><div className="hair"/><div className="face"><i/><i/></div><div className="body"/><div className="arm a1"/><div className="arm a2"/><div className="leg l1"/><div className="leg l2"/></div>}

function App(){
 const [active,setActive]=useState(0), [open,setOpen]=useState<Stop|null>(null), [overview,setOverview]=useState(false), [moving,setMoving]=useState(false)
 const timer=useRef<number|undefined>(undefined)
 const go=(n:number)=>{const next=Math.max(0,Math.min(stops.length-1,n)); if(next===active)return; setMoving(true);setActive(next);window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setMoving(false),550)}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'||e.key==='d')go(active+1);if(e.key==='ArrowLeft'||e.key==='a')go(active-1);if(e.key==='Escape'){setOpen(null);setOverview(false)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[active])
 const current=stops[active]
 return <main style={{'--accent':current.color} as React.CSSProperties}>
  <header><a className="brand" href="#">MINJAE<span>.DEV</span></a><div className="header-center">JAVA · SPRING BACKEND DEVELOPER</div><div className="header-actions"><button onClick={()=>setOverview(true)}><Map size={17}/> 빠르게 보기</button><a href="https://github.com/heopath" target="_blank" rel="noreferrer" aria-label="GitHub"><b>GH</b></a></div></header>
  <section className="scene">
   <div className="sky"><span className="sun"/><span className="cloud c1"/><span className="cloud c2"/></div>
   <div className="chapter-copy"><p>{current.eyebrow}</p><h1>{current.title}</h1><h2>{current.subtitle}</h2><p className="story">{current.story}</p><div className="chips">{current.skills.map(x=><span key={x}>{x}</span>)}</div>{current.project&&<button className="detail" onClick={()=>setOpen(current)}>프로젝트 살펴보기 <ArrowRight size={18}/></button>}</div>
   <div className="world" style={{transform:`translateX(calc(50vw - ${active*260+130}px))`}}>{stops.map((s,i)=><button key={s.id} className={`landmark ${i===active?'active':''}`} style={{left:i*260}} onClick={()=>go(i)} aria-label={`${s.title}로 이동`}><span className="building" style={{'--stop':s.color} as React.CSSProperties}>{s.icon}</span><span className="label">{s.title}</span></button>)}</div>
   <div className="ground"><div className="road"/><div className="char-wrap"><Character moving={moving}/></div></div>
  </section>
  <footer><div className="controls"><button onClick={()=>go(active-1)} disabled={active===0}><ArrowLeft/></button><span><kbd>←</kbd><kbd>→</kbd> 키로 여정을 탐색하세요</span><button onClick={()=>go(active+1)} disabled={active===stops.length-1}><ArrowRight/></button></div><div className="progress"><b>{String(active+1).padStart(2,'0')}</b><span>{stops.map((_,i)=><i key={i} className={i<=active?'on':''}/>)}</span><em>{String(stops.length).padStart(2,'0')}</em></div></footer>
  {open&&<div className="overlay" onClick={()=>setOpen(null)}><article className="modal project-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(null)} aria-label="프로젝트 상세 닫기"><X/></button><span className="modal-icon" style={{background:open.color}}>{open.icon}</span><p>{open.eyebrow}</p><h2>{open.project?.name}</h2><div className="project-meta"><span>{open.project?.period}</span>{open.project?.status&&<span>{open.project.status}</span>}{open.project?.team&&<span>{open.project.team}</span>}</div><p className="modal-story lead">{open.project?.summary}</p><div className="case"><div><small>MY ROLE</small><strong>{open.project?.role}</strong></div><div><small>OUTCOME</small><strong>{open.project?.outcome}</strong></div></div><section className="project-section"><small>PROBLEM SOLVING</small><ul>{open.project?.proof.map(item=><li key={item}><CheckCircle2 size={16}/><span>{item}</span></li>)}</ul></section>{open.project?.metrics&&<section className="project-section"><small>VERIFIED RESULTS</small><div className="metrics">{open.project.metrics.map(item=><strong key={item}>{item}</strong>)}</div></section>}<div className="chips">{open.skills.map(x=><span key={x}>{x}</span>)}</div><div className="project-links">{open.project?.links.map(link=><a key={link.label} className="github-link" href={link.href} target="_blank" rel="noreferrer"><b>{link.label==='GitHub'?'GH':'↗'}</b>{link.label}<ExternalLink size={15}/></a>)}</div></article></div>}
  {overview&&<div className="overlay" onClick={()=>setOverview(false)}><article className="modal overview" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOverview(false)} aria-label="빠르게 보기 닫기"><X/></button><p>QUICK OVERVIEW</p><h2>인프라 경험을,<br/>개발과 배포로 연결합니다.</h2><p className="overview-intro">1년 10개월의 IT 인프라 운영 경험을 바탕으로 Java/Spring 서비스의 데이터 흐름, 배포와 운영을 함께 고민합니다.</p><div className="profile-facts"><span><b>1년 10개월</b>IT 운영 실무</span><span><b>3개</b>대표 프로젝트</span><span><b>Java/Spring</b>희망 직무</span></div><div className="overview-list">{stops.map((s,i)=><button key={s.id} onClick={()=>{go(i);setOverview(false)}}><span style={{background:s.color}}>{s.icon}</span><div><small>{s.eyebrow}</small><strong>{s.title}</strong><em>{s.subtitle}</em></div><ArrowRight/></button>)}</div><div className="overview-contact"><a href="https://github.com/heopath" target="_blank" rel="noreferrer"><b>GH</b> GitHub</a><a href="mailto:heocoding@gmail.com"><Mail size={16}/> heocoding@gmail.com</a></div><div className="source"><BookOpen size={16}/> 입사지원서와 최신 GitHub 프로젝트를 바탕으로 구성했습니다.</div></article></div>}
 </main>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
